feat: add method to read and show keys in the data table from state
liftedinit/gwen pull request #26
Opened 2023-01-24 13:15 UTC by mjsorribas

## Description

Partial Work, Add a method to show the keys in the table on the data-settings page to show arbitrary data (KVStore).

## Related Issue

Fixes # (issue)

## Testing

## Breaking Changes (if applicable)

## Screenshots (if applicable)
![image](https://user-images.githubusercontent.com/1266065/214302880-2f811875-bd8a-4542-b7ea-28d029dc2e05.png)

## Checklist:

- [x] I have read and followed the CONTRIBUTING guidelines for this project.
- [x] I have added or updated tests and they pass.
- [x] I have added or updated documentation and it is accurate.
- [x] I have noted any breaking changes in this module or downstream modules.

2023-01-24 17:07 UTC, stanleyjones requested changes
I don't think this is the right direction. We need to actually fetch the data in order to populate the table, don't we?

2023-01-24 17:07 UTC, stanleyjones commented on src/features/services/components/data-settings.tsx
> +          <Tbody>{KVDataRow(keys)}</Tbody>
I'd do something more like:
```jsx
<Tbody>{keys.map(KVDataRow)}</Tbody>
```
And make `KVDataRow` an actual React component.

2023-01-24 17:07 UTC, stanleyjones commented on src/features/services/components/data-settings.tsx
> +  const keys = useDataServiceStore((s) => s.keys);
I'd suggest doing what I do here instead: https://github.com/stanleyjones/gwen/pull/1

If you do it this way, you'll only get the keys and you want the values too.

2023-01-27 12:18 UTC, mjsorribas commented
closed by developed work in other branch

2023-01-27 12:18 UTC, closed without merging